language: python
python:
- "3.6"
services:
- docker
install:
- set -e
- pip install -r image/base/requirements.txt
script:
- ci/ci.sh
env:
  global:
  - secure: PENnsRg4VqE6nGL06rQZZ41Z02Q4fkopGDRMiA3pT6wB0Spk/nvtfPTQ4JHl6DKoViTGrb9RxI9nUFb8vXdBr2ZOBVyHvMCnRYHtEJrvOOZ/zARGRnUb5AFQQ7cIlgy5AmkQVJv9PxXWO1hfS1TScMEktg55YlY5JqfrWGPhD5eba/O4Ueud0zogXcf27+3c1SgpGuXaGDX/Cwm+YOWnO8KD1Ao99Mx5IJXc6vtXrLuOOUY5qomiUQwtBXk6ZyD7W8H2Nk2FaVthWy8uOvkjzpvDXJsWEr9bjteBKr3SvVT4VEB3tEs3Y29BRzG7IQ3c8Z5/gz31FZkt6V39TvLWbugLs+6Tx8uiquv3QVQGyZ1JSApdVdw5sH46zjkYCu+xNyGvbjVizPISMh4pAJyl5JrC+f8bIdlnofjDc9j9FgXs96PUb5tWn4epnwTfqYeYQPt2Ys7sYD6yPCZfiyt+rAPZV8ol+jTZhLqvTql/WM0zfdj2KFaZNt+BV6u8SQqQ/Sc4hHLuFm6Oaidc4YjsOs18LP77t8oNu/qoFtctKPbPZTrP8E/11MMkhy3mSiaJLhKamJuU+CfKfnlcJd9K9sglG0vl6AZiIWEtg1JLl/ph4z3x4FzfzI+oITmV4KxqGBfCZQ4aEfo33esHAwSORsD/rMFKKaZWjUZVAQflBBE=
  - secure: IJ4TsgILpCtV29cmaI5s9hCsDodH3G8SEXlu17m4L4KxDs/Otpiw/txKUTb2+W+7d0H8jU7d8abRcpmOuNHm9MY7qtoe3E8jMOzpmKcb/108ZzjjVHLuqMEFbIXKmSfCEQq7IqiuA1RSPZdTqcb1mTnhlZjMr+wih4AthmOH9h2QtX+LARy/I9e3HPQ+XXi0EahpQ9lkKj/77HIKmvvwf3n0IlCSthhKwg8MIcSFdJUbFQG2qQ1WRgayh+n3B4V4HBLK99Zy0sRxxMEQ0rT5oiXYN00WxVuvLWxkVEXk/0EX5Goj737NeFW7odQF9DKgBikDCRKQHhy8mf8PNpkCzVBPLGspQpCEUI9+jsSFbhv5TVsJBD+fQlxtRYGwPRZlCoHhS/529QD/C2WTDiFLcfHQ0dyOxQBmDbsuqMh5L/nWcCZmeSFVIrGILQWge0e0OvC95ePcj3GKePmHAJ1nLIJK4C9/3mc3nacbQqwqGgdrfxvAGUtdKIgea3yVuCQgiPbNzrMenaN2O9cA0oMCP6sxmOV3MPxTLkOuOPTRTUNU6McaPjAgYWdjs51j/bbUYX3nIHcJTuJk1FKAN3OC6wkcFUjKdkCrm1nXTtYS2CbmW+FhfbXrPoVtTfCyZQHznnCtqEgxWczObrtrsWYKo6rv3/f03Hj+N1YDSI8+UEk=
